const bcrypt = require('bcryptjs');

/**
 * Verifies a plain-text password against a password hash generated by Laravel.
 * 
 * Laravel uses PHP's password_hash() with the Bcrypt algorithm ($2y$).
 * In Node.js, replacing the $2y$ prefix with $2a$ ensures 100% compatibility 
 * with bcryptjs / bcrypt libraries.
 *
 * @param {string} plainPassword - Plain text password from user request
 * @param {string} hashedPassword - Encrypted password hash stored in DB by Laravel
 * @returns {Promise<boolean>} True if password matches, false otherwise
 */
async function verifyLaravelPassword(plainPassword, hashedPassword) {
  if (!plainPassword || !hashedPassword) {
    return false;
  }

  // Convert PHP $2y$ or $2b$ prefix to $2a$ for Node.js bcrypt compatibility
  const normalizedHash = hashedPassword.replace(/^\$2y\$/, '$2a$');

  return await bcrypt.compare(plainPassword, normalizedHash);
}

module.exports = {
  verifyLaravelPassword
};
